
// Generated by SpriteGenConsole.

#ifndef __SKELETON__
#define __SKELETON__

// Size: 491520 bytes
// Dimensions: 320x96
#define SKELETON_WIDTH 320
#define SKELETON_HEIGHT 96
#define SKELETON_LEN 30720
extern const unsigned short skeleton[SKELETON_LEN];

#endif // __SKELETON__
