
// Generated by SpriteGenConsole.

#ifndef __WALL_STONE__
#define __WALL_STONE__

// Size: 16384 bytes
// Dimensions: 32x32
#define WALL_STONE_WIDTH 32
#define WALL_STONE_HEIGHT 32
#define WALL_STONE_LEN 1024
extern const unsigned short wall_stone[WALL_STONE_LEN];

#endif // __WALL_STONE__
